spring:
  redis:
    host: localhost
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 20
        max-wait: 5000
        max-idle: 8
        min-idle: 0
    timeout: 5000

filter:
  name: test
  expectedInsertions: 1000
  fpp: 0.001