// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bloom.proto

package com.wolfjc.bloom.pb;

public interface BloomFilterReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.BloomFilterReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *编码
   * </pre>
   *
   * <code>string key = 1;</code>
   * @return The key.
   */
  String getKey();
  /**
   * <pre>
   *编码
   * </pre>
   *
   * <code>string key = 1;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();
}
