// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bloom.proto

package com.wolfjc.bloom.pb;

public final class BloomFilter {
  private BloomFilter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_BloomFilterReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_BloomFilterReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_BloomFilterResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_BloomFilterResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013bloom.proto\022\004grpc\"\035\n\016BloomFilterReq\022\013\n" +
      "\003key\030\001 \001(\t\"\"\n\017BloomFilterResp\022\017\n\007isExist" +
      "\030\001 \001(\0102\210\001\n\022BloomFilterService\0228\n\007SaveKey" +
      "\022\024.grpc.BloomFilterReq\032\025.grpc.BloomFilte" +
      "rResp\"\000\0228\n\007IsExist\022\024.grpc.BloomFilterReq" +
      "\032\025.grpc.BloomFilterResp\"\000B,\n\033com.wolfjc." +
      "bloom.example.pbB\013BloomFilterP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_grpc_BloomFilterReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_BloomFilterReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_BloomFilterReq_descriptor,
        new String[] { "Key", });
    internal_static_grpc_BloomFilterResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_BloomFilterResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_BloomFilterResp_descriptor,
        new String[] { "IsExist", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
