// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bloom.proto

package com.wolfjc.bloom.pb;

/**
 * Protobuf type {@code grpc.BloomFilterResp}
 */
public final class BloomFilterResp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc.BloomFilterResp)
    BloomFilterRespOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BloomFilterResp.newBuilder() to construct.
  private BloomFilterResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BloomFilterResp() {
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new BloomFilterResp();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BloomFilterResp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            isExist_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wolfjc.bloom.pb.BloomFilter.internal_static_grpc_BloomFilterResp_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wolfjc.bloom.pb.BloomFilter.internal_static_grpc_BloomFilterResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wolfjc.bloom.pb.BloomFilterResp.class, com.wolfjc.bloom.pb.BloomFilterResp.Builder.class);
  }

  public static final int ISEXIST_FIELD_NUMBER = 1;
  private boolean isExist_;
  /**
   * <pre>
   *是否存在
   * </pre>
   *
   * <code>bool isExist = 1;</code>
   * @return The isExist.
   */
  @Override
  public boolean getIsExist() {
    return isExist_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (isExist_ != false) {
      output.writeBool(1, isExist_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (isExist_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, isExist_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wolfjc.bloom.pb.BloomFilterResp)) {
      return super.equals(obj);
    }
    com.wolfjc.bloom.pb.BloomFilterResp other = (com.wolfjc.bloom.pb.BloomFilterResp) obj;

    if (getIsExist()
        != other.getIsExist()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ISEXIST_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsExist());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wolfjc.bloom.pb.BloomFilterResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wolfjc.bloom.pb.BloomFilterResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wolfjc.bloom.pb.BloomFilterResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wolfjc.bloom.pb.BloomFilterResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wolfjc.bloom.pb.BloomFilterResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wolfjc.bloom.pb.BloomFilterResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wolfjc.bloom.pb.BloomFilterResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wolfjc.bloom.pb.BloomFilterResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wolfjc.bloom.pb.BloomFilterResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.wolfjc.bloom.pb.BloomFilterResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wolfjc.bloom.pb.BloomFilterResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wolfjc.bloom.pb.BloomFilterResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wolfjc.bloom.pb.BloomFilterResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code grpc.BloomFilterResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.BloomFilterResp)
      com.wolfjc.bloom.pb.BloomFilterRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wolfjc.bloom.pb.BloomFilter.internal_static_grpc_BloomFilterResp_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wolfjc.bloom.pb.BloomFilter.internal_static_grpc_BloomFilterResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wolfjc.bloom.pb.BloomFilterResp.class, com.wolfjc.bloom.pb.BloomFilterResp.Builder.class);
    }

    // Construct using com.wolfjc.bloom.pb.BloomFilterResp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      isExist_ = false;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wolfjc.bloom.pb.BloomFilter.internal_static_grpc_BloomFilterResp_descriptor;
    }

    @Override
    public com.wolfjc.bloom.pb.BloomFilterResp getDefaultInstanceForType() {
      return com.wolfjc.bloom.pb.BloomFilterResp.getDefaultInstance();
    }

    @Override
    public com.wolfjc.bloom.pb.BloomFilterResp build() {
      com.wolfjc.bloom.pb.BloomFilterResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public com.wolfjc.bloom.pb.BloomFilterResp buildPartial() {
      com.wolfjc.bloom.pb.BloomFilterResp result = new com.wolfjc.bloom.pb.BloomFilterResp(this);
      result.isExist_ = isExist_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wolfjc.bloom.pb.BloomFilterResp) {
        return mergeFrom((com.wolfjc.bloom.pb.BloomFilterResp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wolfjc.bloom.pb.BloomFilterResp other) {
      if (other == com.wolfjc.bloom.pb.BloomFilterResp.getDefaultInstance()) return this;
      if (other.getIsExist() != false) {
        setIsExist(other.getIsExist());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.wolfjc.bloom.pb.BloomFilterResp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.wolfjc.bloom.pb.BloomFilterResp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean isExist_ ;
    /**
     * <pre>
     *是否存在
     * </pre>
     *
     * <code>bool isExist = 1;</code>
     * @return The isExist.
     */
    @Override
    public boolean getIsExist() {
      return isExist_;
    }
    /**
     * <pre>
     *是否存在
     * </pre>
     *
     * <code>bool isExist = 1;</code>
     * @param value The isExist to set.
     * @return This builder for chaining.
     */
    public Builder setIsExist(boolean value) {
      
      isExist_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *是否存在
     * </pre>
     *
     * <code>bool isExist = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsExist() {
      
      isExist_ = false;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc.BloomFilterResp)
  }

  // @@protoc_insertion_point(class_scope:grpc.BloomFilterResp)
  private static final com.wolfjc.bloom.pb.BloomFilterResp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wolfjc.bloom.pb.BloomFilterResp();
  }

  public static com.wolfjc.bloom.pb.BloomFilterResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BloomFilterResp>
      PARSER = new com.google.protobuf.AbstractParser<BloomFilterResp>() {
    @Override
    public BloomFilterResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BloomFilterResp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BloomFilterResp> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<BloomFilterResp> getParserForType() {
    return PARSER;
  }

  @Override
  public com.wolfjc.bloom.pb.BloomFilterResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

