// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bloom.proto

package com.wolfjc.bloom.pb;

public interface BloomFilterRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.BloomFilterResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *是否存在
   * </pre>
   *
   * <code>bool isExist = 1;</code>
   * @return The isExist.
   */
  boolean getIsExist();
}
